# Generated by Django 5.1.2 on 2024-11-03 15:50

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livros", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categorias",
            options={
                "ordering": ["nome"],
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
            },
        ),
        migrations.AlterModelOptions(
            name="livros",
            options={
                "ordering": ["-criado_em"],
                "verbose_name": "Livro",
                "verbose_name_plural": "Livros",
            },
        ),
        migrations.AddField(
            model_name="livros",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="livros",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="categorias",
            name="nome",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="livros",
            name="categorias",
            field=models.ManyToManyField(related_name="livros", to="livros.categorias"),
        ),
        migrations.AlterField(
            model_name="livros",
            name="nota",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="livros",
            name="streaming",
            field=models.CharField(
                choices=[("F", "Físico"), ("AK", "Amazon Kindle")],
                default="F",
                max_length=2,
            ),
        ),
    ]
