# Generated by Django 5.1.2 on 2024-11-02 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("noivos", "0003_presentes_reservado_por"),
    ]

    operations = [
        migrations.CreateModel(
            name="Acompanhantes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("confirmado", models.BooleanField(default=False)),
                (
                    "convidado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="noivos.convidados",
                    ),
                ),
            ],
        ),
    ]
